# roles/mysql/vars/main.yml

# Databases.
mysql_databases:
  - name: homestead
    collation: utf8_general_ci
    encoding: utf8
    replicate: 1

# Users.
mysql_users:
  - name: homestead
    host: 172.31.8.236
    password: sePret^i
    priv: '*.*:ALL,GRANT'