# roles/mysql/vars/main.yml
mysql_root_password: ""
mysql_databases:
  - name: homestead
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: homestead
    host: "%"
    password: sePret^i
    priv: "*.*:ALL"