---
# tasks file for sonarqube
- name: set max_map
  become: true
  command: sysctl -w vm.max_map_count=262144

- name: set file max
  become: true
  command: sysctl -w fs.file-max=65536

- name: Add max limits
  ansible.builtin.lineinfile:
    path: /etc/security/limits.conf
    line:
      - sonarqube   -   nofile   65536
      - sonarqube   -   nproc    4096
    create: yes

- name: Add the GPG key for the LinuxUpgrading Java PPA
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf1656f24c74cd1d8
    state: present
  become: yes

- name: Add PPA repository for Java
  apt_repository:
    repo: "deb http://ppa.launchpad.net/linuxuprising/java/ubuntu focal main"
    state: present
    update_cache: yes
  become: yes

- name: Install required packages
  ansible.builtin.apt:
    name:
      - python3
      - python3-venv
      - python3-dev
      - libpq-dev
      - openjdk-11-jdk
      - openjdk-11-jre
    state: present

- name: Create a virtual environment
  ansible.builtin.command:
    cmd: python3 -m venv /opt/sonar_venv

- name: Install setuptools in virtual environment
  ansible.builtin.command:
    cmd: /opt/sonar_venv/bin/pip install --upgrade setuptools

- name: Upgrade pip in virtual environment
  ansible.builtin.command:
    cmd: /opt/sonar_venv/bin/pip install --upgrade pip

- name: Install pip dependencies in virtual environment
  ansible.builtin.command:
    cmd: /opt/sonar_venv/bin/pip install psycopg2

- name: Ensure group sonar exists
  ansible.builtin.group:
    name: sonar
    state: present

- import_tasks: postgresql.yml

- import_tasks: sonarqube-setup.yml

- name: Start and enable SonarQube service
  ansible.builtin.service:
    name: sonar
    state: started
    enabled: yes
