---
- name: add PostgreSQL repo to the repo list
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/pgdg.list
    line: "deb http://apt.postgresql.org/pub/repos/apt/ noble-pgdg main"
    create: yes

- name: Download PostgreSQL software key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Update apt package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install PostgreSQL
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present

- name: Start and enable PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes

- name: Set password for user postgres
  ansible.builtin.command:
    cmd: passwd postgres
  args:
    stdin: "postgres\npostgres"

- name: Create SonarQube database
  become_user: postgres
  community.postgresql.postgresql_db:
    name: sonarqube
    encoding: UTF-8

- name: Create SonarQube user
  become_user: postgres
  community.postgresql.postgresql_user:
    name: sonar
    password: sonar
    db: sonarqube
    priv: "ALL"
