---
- hosts: all
  name: Include dynamic variables
  become: yes 
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- name: tooling
  import_playbook: ../static-assignments/webservers.yml
  tags: 
    - webserver

- name: nginx
  import_playbook: ../static-assignments/loadbalancers.yml
  tags:
    - nginx-lb

- name: db
  import_playbook: ../static-assignments/db-servers.yml
  tags:
    -dababase

  
