---
- hosts: all
  name: Include dynamic variables
  become: yes
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always
#- name: tooling
#  import_playbook: ../static-assignments/uat_webservers.yml
#  tags:
#    - webserver

#- name: nginx
#  import_playbook: ../static-assignments/loadbalancers.yml
#  tags:
#    - nginx-lb

#- name: db
#  import_playbook: ../static-assignments/db-servers.yml
#  tags:
#    -database

#- name: artifactory
#  import_playbook: ../static-assignments/artifactory.yml
#  tags:
#    -artifactory

#- name: import sonarqube file
#  import_playbook: ../static-assignments/sonarqube.yml

#- name: todo assignment
#  import_playbook: ../static-assignments/todo.yml
