---
- hosts: all
  name: Include dynamic variables
  become: yes 
  tasks:
    - include_tasks: ../dynamic-assignments/env-vars.yml
      tags:
        - always

- name: uat_webservers
  import_playbook: ../static-assignments/uat_webservers.yml
  tags: 
    - webserver

- name: lb
  import_playbook: ../static-assignments/loadbalancers.yml
  tags:
    - nginx-lb

- name: db-servers
  import_playbook: ../static-assignments/db-servers.yml
  tags:
    -database

  
